apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: degrading-sensor
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: degrading-sensor
  template:
    metadata:
      labels:
        app: degrading-sensor
    spec:
      containers:
        - name: degrading-sensor
          image: degrading-sensor:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intermittent-failures
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intermittent-failures
  template:
    metadata:
      labels:
        app: intermittent-failures
    spec:
      containers:
        - name: intermittent-failures
          image: intermittent-failures:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: success-logs
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: success-logs
  template:
    metadata:
      labels:
        app: success-logs
    spec:
      containers:
        - name: success-logs
          image: success-logs:latest
          imagePullPolicy: IfNotPresent
