[project]
name = "log-sensor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"kubernetes>=32.0.0",
	"sensor-connector",
]

[project.scripts]
log-sensor = "log_sensor:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
sensor-connector = { path = "../../lib/sensor_connector", editable = true }
